name: native_http
description: A package that calls network from native platform ie OkHttp on Android and URLSession iOS.
version: 1.0.0+5
author: Aawaz Gyawali <awazgyawali@gmail.com>
homepage: https://github.com/awazgyawali/native_http

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.brainants.nativehttp.native_http
    pluginClass: NativeHttpPlugin
